/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "bin2grey.v:1.1-5.10" *)
module bin2grey(bin, grey);
  (* src = "bin2grey.v:2.12-2.15" *)
  input [3:0] bin;
  wire [3:0] bin;
  (* src = "bin2grey.v:3.13-3.17" *)
  output [3:0] grey;
  wire [3:0] grey;
  assign grey[1] = bin[1] ^ bin[2];
  assign grey[0] = bin[1] ^ bin[0];
  assign grey[2] = bin[2] ^ bin[3];
  assign grey[3] = bin[3];
endmodule
