/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "halfadder.v:1.1-6.10" *)
module half_adder(a, b, sum, cout);
  (* src = "halfadder.v:2.7-2.8" *)
  input a;
  wire a;
  (* src = "halfadder.v:2.9-2.10" *)
  input b;
  wire b;
  (* src = "halfadder.v:3.8-3.11" *)
  output sum;
  wire sum;
  (* src = "halfadder.v:3.12-3.16" *)
  output cout;
  wire cout;
  (* src = "halfadder.v:2.7-2.8" *)
  wire _0_;
  (* src = "halfadder.v:2.9-2.10" *)
  wire _1_;
  (* src = "halfadder.v:3.12-3.16" *)
  wire _2_;
  (* src = "halfadder.v:3.8-3.11" *)
  wire _3_;
  assign _2_ = _0_ & _1_;
  assign _3_ = _0_ ^ _1_;
  assign _0_ = a;
  assign _1_ = b;
  assign cout = _2_;
  assign sum = _3_;
endmodule
