/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "carrylookadder.v:1.1-19.10" *)
module carrylookadder(a, b, sum, cout);
  (* src = "carrylookadder.v:2.12-2.13" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "carrylookadder.v:2.14-2.15" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "carrylookadder.v:3.14-3.17" *)
  output [3:0] sum;
  wire [3:0] sum;
  (* src = "carrylookadder.v:4.8-4.12" *)
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "carrylookadder.v:6.6-6.8" *)
  wire p0;
  assign _00_ = ~(a[3] & b[3]);
  assign _01_ = a[3] | b[3];
  assign _02_ = ~(a[2] & b[2]);
  assign _03_ = ~(a[1] & b[1]);
  assign _04_ = a[0] & b[0];
  assign _05_ = a[1] ^ b[1];
  assign _06_ = ~(_04_ & _05_);
  assign _07_ = ~(_03_ & _06_);
  assign _08_ = a[2] ^ b[2];
  assign _09_ = ~(_07_ & _08_);
  assign _10_ = ~(_02_ & _09_);
  assign _11_ = ~(_01_ & _10_);
  assign cout = ~(_00_ & _11_);
  assign sum[2] = _07_ ^ _08_;
  assign _12_ = ~(_00_ & _01_);
  assign sum[3] = ~(_10_ ^ _12_);
  assign sum[1] = _04_ ^ _05_;
  assign p0 = a[0] ^ b[0];
  assign sum[0] = p0;
endmodule
