/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "m2u1x.v:1.1-11.10" *)
module mux21(in, sel, out);
  (* src = "m2u1x.v:2.12-2.14" *)
  input [1:0] in;
  wire [1:0] in;
  (* src = "m2u1x.v:3.7-3.10" *)
  input sel;
  wire sel;
  (* src = "m2u1x.v:4.8-4.11" *)
  output out;
  wire out;
  assign out = sel ? in[1] : in[0];
endmodule
